version: "3.8"

services:
  db:
    image: postgres:13
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db:/var/lib/db
  app:
    build: .
    ports:
      - 9000:9000
    image: medusa.be:1.0
    env_file: ./.env
    depends_on:
      - db
    environment:
      - JWT_SECRET=$JWT_SECRET
      - COOKIE_SECRET=$COOKIE_SECRET
      - DATABASE_TYPE="postgres"
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
      - MEDUSA_FF_PRODUCT_CATEGORIES=true
      - CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET
volumes:
  db:
